### ISSUE TITLE
How to view the graph format file

### ISSUE THREAD

**Issue by Junkai-Liu** [xipengwang/aprilSAM#1]
I am confused about the M3500.graph file of graph format in the folder of dataset,how can i view this kind of file.

**Comment by xipengwang** [comment]
We directly write data bytes into the graph file. You can create a graph using `april_graph_t* april_graph_create_from_file(const char *path)`. 
It essentially contains same information as M3500.txt.

**Comment by Junkai-Liu** [comment]
Thank you for your reply .
