### ISSUE TITLE
what's the storage format of covariance in M3500.txt  

### ISSUE THREAD

**Issue by Junkai-Liu** [xipengwang/aprilSAM#3]
like g2o format data ,covariance matrix merely storage its upper triangular in order to save space.note the real number as symbol a,therefore,the storage format is a 00000 a 0000 a 000 a 00 a(illustrate as SE(3));
while your data such as :a 0 a a 0 0,the covariance matrix should be a diagonal matrix,right? I can't see the covariance element storage order.

**Comment by xipengwang** [comment]
It is [I00  I01  I11  I22  I02  I12]. It is a little bit weird. Basically, the non-zero elements are the diagonal elements for the covariance matrix.
